language: generic

notifications:
  email: false

env:
  - PYTHON_VERSION=3.5 CC=gcc-7 CXX=g++-7
  - PYTHON_VERSION=3.6 CC=gcc-7 CXX=g++-7
  # disabled until all conda packages exist for Python 3.7
  # - PYTHON_VERSION=3.7

# conda setup copied from the conda docs
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON_VERSION numpy pandas
  - source activate test-environment
  - pip install -r requirements.txt
  - conda install -y -c pennmem -c conda-forge classiflib ptsa
  - python setup.py install

script:
  - flake8
  - python -m pytest -m "not rhino"

after_success:
  - codecov
